steps:
  - retriever:
      name: embedding
      model_name: intfloat/multilingual-e5-large
      top_k: 50
      cache: ./cache/multilingual-e5-large
      knowledge_base:
        name: multiclaim
        crosslingual: False
        fact_check_language: None
        language: None
        post_language: None
        split: None
        version: original
  - prompt:
      type: pointwise
      template: 'Claim: {document}\n\nPost: {query}\n\nIs the claim relevant to the social media post? Respond with a single word, either "Yes" or "No", in English only.'
  - llm:
      model: hf_model
      model_name: CohereForAI/c4ai-command-r-plus-4bit
      max_new_tokens: 1
      device_map: auto
      load_in_4bit: False
      system_prompt: None
  - postprocessor:
      name: pointwise_postprocessor